#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_


#define USE_SOFTETH_ON_ZYNQ 0
//#define PLATFORM_EMAC_BASEADDR XPAR_AXI_ETHERNET_0_BASEADDR
#define PLATFORM_EMAC_BASEADDR XPAR_XEMACPS_1_BASEADDR

#define PLATFORM_ZYNQ 


#endif
